export const webFonts = [
  'Arial',
  'Arial Black',
  'Century Gothic',
  'Comic Sans MS',
  'Courier',
  'Courier New',
  'Geneva',
  'Georgia',
  'Lucida',
  'Lucida Console',
  'Lucida Grande',
  'Lucida Sans',
  'Monaco',
  'MS Serif',
  'New York',
  'Palatino',
  'Palatino Linotype',
  'Tahoma',
  'Times',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
];
